#!/bin/bash

#
# Start container with Firefox Docker image
#
# Author: Björn Hendriks, 2019
#
# Params
# 	1: (optional) shared folder mounted into container's download folder
# 	2: (optional) Name for the container. If given the container will be
# 	   persistent. You have to take care to remove it or may later restart
# 	   it.
#

# The default shared mem size of 64m is not sufficient for vidoes
# The shared mem size could also be passed to the docker build call and maybe
# set in the Dockerfile.
shmSize=1g

. $(dirname $0)/config

# Make Docker run option for download folder
hostDownloadFolder=$1
if [ -d $hostDownloadFolder ]
then
	downloadFolderOption="-v $hostDownloadFolder:/home/$userName/Downloads"
else
	downloadFolderOption=""
fi

# Make container persistent with given name
name=$2
if [ -z $name ]
then
	rmOpt="--rm"
	nameOpt=""
else
	rmOpt=""
	nameOpt="--name $name"
fi

# Local user ID
hostUserId=$(id -u)

pulseDir=/run/user/$hostUserId/pulse

# Run Docker container such that it shares display and sound server with the host
#
# --rm               remove container when last process (browser window) terminates
# -e DISPLAY         pass DISPLAY environment variable for graphical output
# -e PULSE_SERVER    pass path to host user's sound socket
# -v /tmp/.X11-unix  map host's display sockets into container
# --shm-size         set shared memory szie (see above)
# -v /run/user/$hostUserId/pulse  map host user's sound socket into container
# $downloadFolderOption  see above
# $tagName           see config file
docker run $rmOpt $nameOpt -e DISPLAY -e PULSE_SERVER=unix:$pulseDir/native -v /tmp/.X11-unix:/tmp/.X11-unix --shm-size $shmSize -v $pulseDir:/run/user/$userId/pulse $downloadFolderOption $tagName

